# Build

FROM mcr.microsoft.com/dotnet/sdk:10.0 AS builder

WORKDIR /build

RUN git clone --depth=1 \
    https://codeberg.org/rewio/ServerS4A12.git \
    ServerS4A12

WORKDIR /build/ServerS4A12

RUN dotnet build Server/DfoServer.sln -c Debug


RUN cp start-server.sh Server/DfoServer/bin/Debug/ \
    && chmod +x Server/DfoServer/bin/Debug/start-server.sh \
    && mkdir -p /output \
    && cp -a Server/DfoServer/bin/Debug/. /output/


#run

FROM mcr.microsoft.com/dotnet/runtime:10.0

WORKDIR /dxf

COPY --from=builder /output/ /dxf/

RUN chmod +x /dxf/start-server.sh

CMD ["bash", "./start-server.sh"]